/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManagePatient;

import NewPatient.Controller;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author robeszpierre
 */
public class ManageMain extends javax.swing.JFrame {
    

    int idNumber;
    
    /**
     * Creates new form ManageMain
     */
    public ManageMain(int id) {
        this.setVisible(true);
        this.idNumber = id;
        String path=Controller.controller.path + "/" + idNumber + "/";
        initComponents();
        jScrollPane1.setBorder(null);
        jScrollPane2.setBorder(null);
        jScrollPane3.setBorder(null);
        jScrollPane4.setBorder(null);
        jScrollPane5.setBorder(null);
        jScrollPane6.setBorder(null);
        jScrollPane7.setBorder(null);
        
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        jTextArea1.setBorder(null);
        jTextArea1.setBackground(new Color(0,0,0,0));
        
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setOpaque(false);
        jScrollPane2.setBorder(null);
        jScrollPane2.setViewportBorder(null);
        jTextArea2.setBorder(null);
        jTextArea2.setBackground(new Color(0,0,0,0));
        
        jScrollPane3.getViewport().setOpaque(false);
        jScrollPane3.setOpaque(false);
        jScrollPane3.setBorder(null);
        jScrollPane3.setViewportBorder(null);
        jTextArea3.setBorder(null);
        jTextArea3.setBackground(new Color(0,0,0,0));
        
        jScrollPane4.getViewport().setOpaque(false);
        jScrollPane4.setOpaque(false);
        jScrollPane4.setBorder(null);
        jScrollPane4.setViewportBorder(null);
        jTextArea4.setBorder(null);
        jTextArea4.setBackground(new Color(0,0,0,0));
        
        jScrollPane5.getViewport().setOpaque(false);
        jScrollPane5.setOpaque(false);
        jScrollPane5.setBorder(null);
        jScrollPane5.setViewportBorder(null);
        jTextArea5.setBorder(null);
        jTextArea5.setBackground(new Color(0,0,0,0));
        
        jScrollPane6.getViewport().setOpaque(false);
        jScrollPane6.setOpaque(false);
        jScrollPane6.setBorder(null);
        jScrollPane6.setViewportBorder(null);
        jTextArea6.setBorder(null);
        jTextArea6.setBackground(new Color(0,0,0,0));
        
        loadSymptoms();
        

        try {
            Scanner personalDataInput=new Scanner(new File(path+"personaldata.txt"));
            personalDataInput.nextLine();
            jTextArea7.append("Név: " + personalDataInput.nextLine() + "\n\n");
            jTextArea7.append("Anyja neve: " + personalDataInput.nextLine() + "\n\n");
            jTextArea7.append("Születési hely: " + personalDataInput.nextLine() + "\n\n");
            jTextArea7.append("Születési időpont: " + personalDataInput.nextLine() + "\n\n");
            jTextArea7.append("Családi állapot: " + personalDataInput.nextLine() + "\n\n");
            jTextArea7.append("Foglalkozás: " + personalDataInput.nextLine() + "\n\n");
            jTextArea7.append("E-mail cím: " + personalDataInput.nextLine() + "\n\n");
            jTextArea7.append("Telefonszám: " + personalDataInput.nextLine() + "\n\n");
            jTextArea7.append("Neme: " + personalDataInput.nextLine() + "\n\n");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManageMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();

        setTitle("Betegek kezelése");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("FEJ");
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jTextArea1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(50, 120, 280, 100);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setToolTipText("FEJ");
        jTextArea3.setBorder(null);
        jTextArea3.setOpaque(false);
        jTextArea3.setRequestFocusEnabled(false);
        jScrollPane3.setViewportView(jTextArea3);
        jTextArea3.getAccessibleContext().setAccessibleDescription("MELLKAS");

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(50, 230, 280, 110);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setToolTipText("FEJ");
        jTextArea2.setBorder(null);
        jTextArea2.setOpaque(false);
        jTextArea2.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(50, 0, 220, 110);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setToolTipText("FEJ");
        jTextArea4.setBorder(null);
        jTextArea4.setOpaque(false);
        jTextArea4.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(50, 480, 203, 160);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setToolTipText("FEJ");
        jTextArea5.setBorder(null);
        jTextArea5.setOpaque(false);
        jTextArea5.setRequestFocusEnabled(false);
        jScrollPane5.setViewportView(jTextArea5);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(350, 480, 203, 160);

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setToolTipText("FEJ");
        jTextArea6.setOpaque(false);
        jTextArea6.setRequestFocusEnabled(false);
        jScrollPane6.setViewportView(jTextArea6);

        jPanel2.add(jScrollPane6);
        jScrollPane6.setBounds(50, 350, 320, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ManagePatient/body3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 680);

        jTabbedPane1.addTab("Tünetek", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea7.setRows(5);
        jScrollPane7.setViewportView(jTextArea7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Személyes adatok", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("tab1", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("tab1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    // End of variables declaration//GEN-END:variables

    private void loadSymptoms() {
        String path=Controller.controller.path + "/" + idNumber + "/";
        Scanner frequentInput=null;
        Scanner rareInput=null;
        String path1=path+"frequent.txt";
        String path2=path+"rare.txt";
        try {
            frequentInput = new Scanner(new File(path1));
            rareInput = new Scanner(new File(path2));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManageMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //HEAD
        
        String line = frequentInput.nextLine();
        while(!line.equals("*****")){
            jTextArea1.append(line+"\n");
            line = frequentInput.nextLine();
        }
        String line2 = rareInput.nextLine();
        while(!line2.equals("*****")){
            jTextArea1.append(line2+"\n");
            line2 = rareInput.nextLine();
        }
        
        //CHEST
        
        line = frequentInput.nextLine();
        while(!line.equals("*****")){
            jTextArea2.append(line+"\n");
            line = frequentInput.nextLine();
        }
        line2 = rareInput.nextLine();
        while(!line2.equals("*****")){
            jTextArea2.append(line2+"\n");
            line2 = rareInput.nextLine();
        }
        
        
        //BELLY
        
        line = frequentInput.nextLine();
        while(!line.equals("*****")){
            jTextArea6.append(line+"\n");
            line = frequentInput.nextLine();
        }
        line2 = rareInput.nextLine();
        while(!line2.equals("*****")){
            jTextArea6.append(line2+"\n");
            line2 = rareInput.nextLine();
        }
        jTextArea6.append("\n");
        line = frequentInput.nextLine();
        while(!line.equals("*****")){
            jTextArea6.append(line+"\n");
            line = frequentInput.nextLine();
        }
        line2 = rareInput.nextLine();
        while(!line2.equals("*****")){
            jTextArea6.append(line2+"\n");
            line2 = rareInput.nextLine();
        }
        
        
        //LOWER ABDOMEN
        
        line = frequentInput.nextLine();
        while(!line.equals("*****")){
            jTextArea3.append(line+"\n");
            line = frequentInput.nextLine();
        }
        line2 = rareInput.nextLine();
        while(!line2.equals("*****")){
            jTextArea3.append(line2+"\n");
            line2 = rareInput.nextLine();
        }
        jTextArea3.append("\n");
        line = frequentInput.nextLine();
        while(!line.equals("*****")){
            jTextArea3.append(line+"\n");
            line = frequentInput.nextLine();
        }
        line2 = rareInput.nextLine();
        while(!line2.equals("*****")){
            jTextArea3.append(line2+"\n");
            line2 = rareInput.nextLine();
        }
        
        //SPINE
        
        line = frequentInput.nextLine();
        while(!line.equals("*****")){
            jTextArea4.append(line+"\n");
            line = frequentInput.nextLine();
        }
        
        //EXTREMITIES
        
        line = frequentInput.nextLine();
        while(!line.equals("*****")){
            jTextArea5.append(line+"\n");
            line = frequentInput.nextLine();
        }
        
        frequentInput.close();
        rareInput.close();
    }
}
