package Main;

import ManagePatient.ManageMain;
import ManagePatient.SelectPatient;
import NewPatient.Controller;
import Statistic.Statistic;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.lang.reflect.Field;
import java.nio.charset.Charset;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author robeszpierre
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        System.setProperty("file.encoding","UTF-8");
            Field charset = null;
        try {
            charset = Charset.class.getDeclaredField("defaultCharset");
        } catch (NoSuchFieldException | SecurityException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            charset.setAccessible(true);
        try {
            charset.set(null,null);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        BufferedImage img=null;   
        Image dimg=null;
        int numOfFiles=new File(Controller.controller.path+"img"+File.separatorChar+"main").listFiles().length;
        System.out.println(numOfFiles);
        Random rand = new Random();
        int randomPicture = rand.nextInt(numOfFiles) + 1;
        try{
            img=ImageIO.read(new File(Controller.controller.path+"img"+File.separatorChar+"main"+File.separatorChar+randomPicture+".jpg"));
            dimg = img.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(),
            Image.SCALE_SMOOTH);
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Nincs a Patients mappa a megfelelő helyen. Ha nem tudja megoldani a problémát, akkor kérem lépjen kapcsolatba a fejlesztővel a robeszpierre@gmail.com e-mail címen.");
        }
        
        ImageIcon icon=new ImageIcon(dimg);
        jLabel1.setIcon(icon);

        
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        newPatientButton = new javax.swing.JButton();
        existingPatientButton = new javax.swing.JButton();
        statisticButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beteg nyílvántartó");
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(146, 146, 146));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 400));
        mainPanel.setLayout(null);

        newPatientButton.setBackground(new java.awt.Color(0, 0, 0));
        newPatientButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        newPatientButton.setForeground(new java.awt.Color(255, 255, 255));
        newPatientButton.setText("Új beteg felvétele");
        newPatientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newPatientButtonMouseClicked(evt);
            }
        });
        mainPanel.add(newPatientButton);
        newPatientButton.setBounds(120, 100, 240, 100);

        existingPatientButton.setBackground(new java.awt.Color(0, 0, 0));
        existingPatientButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        existingPatientButton.setForeground(new java.awt.Color(255, 255, 255));
        existingPatientButton.setText("Betegek kezelése");
        existingPatientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                existingPatientButtonMouseClicked(evt);
            }
        });
        mainPanel.add(existingPatientButton);
        existingPatientButton.setBounds(120, 260, 240, 100);

        statisticButton.setBackground(new java.awt.Color(0, 0, 0));
        statisticButton.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        statisticButton.setForeground(new java.awt.Color(255, 255, 255));
        statisticButton.setText("Statisztika");
        statisticButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticButtonMouseClicked(evt);
            }
        });
        mainPanel.add(statisticButton);
        statisticButton.setBounds(1020, 580, 240, 100);
        mainPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPatientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newPatientButtonMouseClicked
         Controller.controller.newPatient();
    }//GEN-LAST:event_newPatientButtonMouseClicked

    private void existingPatientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_existingPatientButtonMouseClicked
        SelectPatient selectPatient = new SelectPatient();
        selectPatient.setVisible(true);
    }//GEN-LAST:event_existingPatientButtonMouseClicked

    private void statisticButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticButtonMouseClicked
        this.setVisible(false);
        
        Statistic statistic = new Statistic();
        statistic.setExtendedState(JFrame.MAXIMIZED_BOTH);
        statistic.setVisible(true);
    }//GEN-LAST:event_statisticButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton existingPatientButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newPatientButton;
    private javax.swing.JButton statisticButton;
    // End of variables declaration//GEN-END:variables

    
}
